console.log("IF ANYONE TOLD YOU TO COPY PASTE SOMETHING IN HERE DO NOT DO IT!!!")
console.log("I WILL NOT TAKE RESPONSIBILITY FOR ANYTHING!")
console.log("ONLY WRITE SOMETHING IN HERE IF YOU KNOW WHAT YOU'RE DOING!")